Repository uwblueprint/social-diversity-for-children, pull requests merged in 2021-12, with the labels that each got.

#170 feat(admin/dashboard): make dashboard responsive with new button
  pages/admin/index.tsx
  src/components/admin/AdminOptionButton.tsx
  src/components/admin/AdminStatBox.tsx
  src/components/admin/UpcomingClassCard.tsx
Labels: need dev review, need designer review, design stamped

#169 fix: use DateTime instead of raw startTimeMinutes to fix timezone issue
  pages/api/class/upcoming.ts
  pages/api/enroll/child.ts
  pages/api/mail/index.ts
  prisma/schema.prisma
  prisma/schema.sql
  services/database/class.ts
  src/components/ClassInfoCard.tsx
  src/components/ClassInfoModal.tsx
  src/components/EnrollmentCard.tsx
  src/components/FormClass.tsx
  src/components/VolunteeringCard.tsx
  src/components/WaitlistCard.tsx
  src/components/admin/ArchivedProgramClassInfoCard.tsx
  src/components/admin/ClassViewInfoCard.tsx
  src/components/admin/LiveClassCard.tsx
  src/components/admin/ProgramClassInfoCard.tsx
  src/components/admin/UpcomingClassCard.tsx
  utils/cardInfoUtil.ts
  utils/enum/weekday.ts
  utils/mail/templateUtil.ts
  utils/time/convert.ts
Labels: need dev review

#172 feat(archive-class): remove link to unarchived page + query only unarchived class by default
  pages/api/class/[id].ts
  services/database/class.ts
  src/components/admin/ArchivedProgramClassInfoCard.tsx
  utils/hooks/useClass.ts
Labels: need dev review, need designer review

#164 chore(translate): change for auto-discount remove
  pages/parent/enrollment.tsx
  public/locales/en/common.json
  public/locales/en/form.json
Labels: need dev review

#171 feat(translate): update login/verify + static date
  .github/workflows/ci-pr.yml
  .github/workflows/ci-push.yml
  pages/login.tsx
  pages/verify.tsx
  public/locales/en/common.json
Labels: need dev review

#160 Create Program and Class Pages
  models/Class.ts
  models/Program.ts
  package.json
  pages/admin/class/edit/[id].tsx
  pages/admin/program/edit/[id].tsx
  pages/admin/program/index.tsx
  pages/api/class/index.ts
  pages/api/class/upcoming.ts
  pages/api/enroll/child.ts
  pages/api/file/upload.ts
  pages/api/mail/index.ts
  pages/api/price/[priceId].ts
  pages/api/program/[id].ts
  pages/api/program/index.ts
  prisma/schema.prisma
  prisma/schema.sql
  services/database/class.ts
  services/database/program-card-info.ts
  services/database/program.ts
  src/components/ClassInfoCard.tsx
  src/components/ClassInfoModal.tsx
  src/components/EnrollmentCard.tsx
  src/components/FormClass.tsx
  src/components/ProgramCard.tsx
  src/components/VolunteeringCard.tsx
  src/components/WaitlistCard.tsx
  src/components/admin/AdminOptionButton.tsx
  src/components/admin/ArchivedBrowseProgramCard.tsx
  src/components/admin/ArchivedProgramClassInfoCard.tsx
  src/components/admin/ArchivedProgramViewInfoCard.tsx
  src/components/admin/BrowseProgramCard.tsx
  src/components/admin/ClassViewInfoCard.tsx
  src/components/admin/LiveClassCard.tsx
  src/components/admin/ProgramClassInfoCard.tsx
  src/components/admin/ProgramViewInfoCard.tsx
  src/components/admin/UpcomingClassCard.tsx
  src/components/formFields/DateField.tsx
  src/components/formFields/MuitipleTextField.tsx
  src/components/formFields/SelectField.tsx
  src/components/formFields/UploadField.tsx
  utils/cardInfoUtil.ts
  utils/enum/weekday.ts
  utils/hooks/useClass.ts
  utils/hooks/useProgramIncludeArchived.ts
  utils/hooks/useStripePrice.ts
  utils/mail/templateUtil.ts
  utils/time/convert.ts
  yarn.lock
Labels: need dev review, need designer review, design stamped

#184 feat(admin): upcoming classes page
  pages/admin/archive/index.tsx
  pages/admin/class/[id].tsx
  pages/admin/index.tsx
  pages/admin/program/[pid].tsx
  pages/admin/upcoming.tsx
Labels: need designer review, design stamped, small

#188 fix(prisma-query): parent query order students id
  services/database/user.ts
Labels: bug, need dev review, cleanup, small

#187 fix: 404 page support static translation
  pages/404.tsx
  public/locales/en/common.json
  public/locales/ja/common.json
  public/locales/ja/form.json
Labels: bug, need dev review, cleanup

#186 fix(program-details): volunteer spots prog details instead of participant
  src/components/ClassInfoCard.tsx
Labels: bug, need dev review, cleanup

#189 feat(teacher): allow viewing of registered stu/vol
  pages/admin/registrant/user/[id].tsx
  pages/api/user/[id].ts
  services/database/enroll.ts
  utils/hooks/useStudentRegTableData.tsx
  utils/hooks/useVolunteerRegTableData.tsx
  utils/session/authorization.ts
Labels: need dev review, need designer review, design stamped

#190 fix(external enroll): no dup enrollment
  pages/class.tsx
  pages/parent/enrollment.tsx
  pages/volunteer/enrollment.tsx
Labels: bug, small

#191 fix(volunteer signup): doc-upload page +continue
  pages/document-upload.tsx
Labels: bug, small

#192 fix(internal/browse): fix width styling for cards
  src/components/admin/ClassViewInfoCard.tsx
  src/components/admin/ProgramViewInfoCard.tsx
Labels: bug, cleanup

#193 fix(internal/api): filter ended classes upcoming
  services/database/class.ts
Labels: bug, small

#195 fix(api): update document resets approved
  prisma/schema.sql
  services/database/user.ts
Labels: bug, cleanup

#197 chore(api): add proper RBAC for api to reduce access
  README.md
  pages/api/class/[id].ts
  pages/api/class/index.ts
  pages/api/class/meeting.ts
  pages/api/enroll/child.ts
  pages/api/enroll/volunteer.ts
  pages/api/program/[id].ts
  pages/api/program/index.ts
  pages/api/user/[id].ts
  pages/api/user/index.ts
Labels: need dev review, cleanup

#175 Adding confirmation modal to class unregister
  public/locales/en/common.json
  src/components/EnrollmentCard.tsx
Labels: need dev review, need designer review, design stamped

#213 fix(class-cards): add mobile responsive
  src/components/ClassInfoCard.tsx
  src/components/FormClass.tsx
  src/components/VolunteeringCard.tsx
Labels: need dev review, need designer review

#177 external/internal changes showing expired crim checks
  pages/admin/registrant/user/[id].tsx
  public/locales/en/common.json
  src/components/MissingDocAlert.tsx
  src/components/fileDownloadCard.tsx
  src/components/myAccounts/CriminalCheck.tsx
  utils/checkExpiry.ts
  utils/hooks/useVolunteerRegTableData.tsx
  utils/hooks/useVolunteersTableData.tsx
Labels: need dev review, good to merge, dev stamped

#217 fix(signup): save upload file link via query param
  models/User.ts
  pages/document-upload.tsx
  pages/parent/signup.tsx
  pages/volunteer/enrollment.tsx
  pages/volunteer/signup.tsx
  services/database/user.ts
  utils/validation/user.ts
Labels: bug, need dev review, cleanup

#218 feat(myaccounts): add link to open uploaded doc
  pages/myaccounts.tsx
  public/locales/en/common.json
  src/components/myAccounts/CriminalCheck.tsx
  src/components/myAccounts/ProofOfIncome.tsx
Labels: need dev review, small
