Repository uwblueprint/social-diversity-for-children, pull requests merged in 2021-11, with the labels that each got.

#121 Update eslint and prettier commands
  .eslintrc
  .github/workflows/ci.yml
  .prettierrc
  package.json
Labels: good to merge

#125 [Bug Fixes] Trim input to text fields & fix parent registration message
  src/components/formFields/TextField.tsx
  src/components/parent-form/ParentCreatedPage.tsx
Labels: need dev review, good to merge, dev stamped

#122 feat(class,program,accounts): add responsive design
  pages/myaccounts.tsx
  src/components/ClassInfoCard.tsx
  src/components/ClassInfoModal.tsx
  src/components/EnrollmentCard.tsx
  src/components/ProgramInfo.tsx
  src/components/SDCWrapper.tsx
Labels: need dev review, need designer review, design stamped

#123 feature - waitlist
  models/Enroll.ts
  pages/api/waitlist/index.ts
  pages/class.tsx
  services/database/waitlist.ts
  src/components/ClassInfoCard.tsx
  src/components/ClassInfoModal.tsx
  src/components/ClassList.tsx
  src/components/WaitlistCard.tsx
  src/components/WaitlistList.tsx
  utils/cardInfoUtil.ts
  utils/createWaitlistRegistration.ts
  utils/deleteWaitlistRegistration.ts
  utils/useParentWaitlist.ts
Labels: need dev review, need designer review, design stamped, dev stamped

#134 feat(admin view registrants): page + hooks
  pages/admin/index.tsx
  pages/admin/registrant/index.tsx
  src/components/AdminWrapper.tsx
  utils/hooks/useParentsTableData.tsx
  utils/hooks/useStudentsTableData.tsx
  utils/hooks/useUser.ts
  utils/hooks/useUsers.ts
  utils/hooks/useVolunteersTableData.tsx
Labels: need dev review, need designer review

#129 Bug fix: change descriptions for some success messages
  pages/parent/participant.tsx
  src/components/parent-form/ParticipantCreatedPage.tsx
  src/components/registration-form/ParentEnrolledConfirmationPage.tsx
Labels: bug

#135 feat(admin signup): invite teachers and admins internally
  models/User.ts
  pages/admin/add.tsx
  pages/api/user/index.ts
  pages/volunteer/enrollment.tsx
  services/database/user.ts
  src/components/admin/ClassViewInfoCard.tsx
  src/components/formFields/TextField.tsx
  src/components/registration-form/ParentEnrolledConfirmationPage.tsx
  utils/createUser.ts
Labels: need dev review, need designer review, design stamped

#136 feat(admin browse internal users): table page and button to revoke/delete user
  pages/admin/add.tsx
  pages/admin/class/[id].tsx
  pages/admin/index.tsx
  pages/admin/registrant/index.tsx
  pages/admin/user.tsx
  pages/api/admin/stats.ts
  pages/api/class/[id].ts
  pages/api/class/archive/[classId].ts
  pages/api/class/registrant/[classId].ts
  pages/api/user/[id].ts
  pages/api/user/index.ts
  pages/myaccounts.tsx
  pages/parent/participant.tsx
  prisma/dev-seeds/user.ts
  prisma/schema.prisma
  prisma/schema.sql
  services/database/user.ts
  types/next-auth.d.ts
  types/react-table-config.d.ts
  utils/deleteUser.ts
  utils/hooks/useAdminsTableData.tsx
  utils/hooks/useParentsTableData.tsx
  utils/hooks/useStudentRegTableData.tsx
  utils/hooks/useStudentsTableData.tsx
  utils/hooks/useTeachersTableData.tsx
  utils/hooks/useUsers.ts
  utils/hooks/useVolunteerRegTableData.tsx
  utils/hooks/useVolunteersTableData.tsx
  utils/parsePhoneNumber.ts
  utils/session/authorization.ts
Labels: design stamped

#137 feature - send waitlist emails when parent unregisters from class
  pages/api/enroll/child.ts
  services/database/enroll.ts
  services/database/waitlist.ts
  utils/mail/templateWaitlist.ts
Labels: need dev review, need changes, design stamped, dev stamped

#138 fix(admin volunteer table): pending state to volunteer table
  README.md
  pages/admin/add.tsx
  utils/hooks/useVolunteerRegTableData.tsx
  utils/hooks/useVolunteersTableData.tsx
Labels: need designer review, design stamped, cleanup

#141 feat(session sensitive sidebar): component tweak
  pages/404.tsx
  pages/admin/add.tsx
  pages/admin/index.tsx
  pages/admin/registrant/index.tsx
  pages/admin/user.tsx
  pages/class.tsx
  pages/document-upload.tsx
  pages/index.tsx
  pages/myaccounts.tsx
  pages/parent/enrollment.tsx
  pages/parent/participant.tsx
  pages/parent/signup.tsx
  pages/program-details/[pid].tsx
  pages/signup.tsx
  pages/volunteer/enrollment.tsx
  pages/volunteer/signup.tsx
  src/components/AdminWrapper.tsx
  src/components/CommonError.tsx
  src/components/CommonLoading.tsx
  src/components/Navbar.tsx
  src/components/ProgramCard.tsx
  src/components/ProgramInfo.tsx
  src/components/SDCWrapper.tsx
  src/components/WelcomeToSDC.tsx
  src/components/parent-form/ParentCreatedPage.tsx
  src/components/parent-form/ParticipantCreatedPage.tsx
  src/components/registration-form/ParentEnrollFormWrapper.tsx
  src/components/volunteer-enroll/VolunteerEnrollFormWrapper.tsx
  src/components/volunteer-form/VolunteerCreatedPage.tsx
Labels: need dev review, need designer review, cleanup

#126 Created Criminal Check Admin Page
  models/User.ts
  pages/admin/registrant/user/[id].tsx
  pages/api/admin/update-criminal-check-status.ts
  pages/api/file/retrieve/index.ts
  prisma/dev-seeds/parent.ts
  prisma/schema.prisma
  prisma/schema.sql
  services/database/user.ts
  src/components/EmptyState.tsx
  src/components/fileDownloadCard.tsx
  utils/enum/filetype.ts
  utils/fetcher.ts
  utils/hooks/useFileRetrieve.ts
  utils/updateFileApproval.ts
Labels: need dev review, need designer review, need changes, design stamped, dev stamped

#131 Implement admin browse programs page
  .github/workflows/ci.yml
  pages/admin/program/index.tsx
  src/components/BrowseProgramCard.tsx
  src/components/ProgramDescriptionCard.tsx
  src/components/admin/AdminHeader.tsx
Labels: need dev review, need changes, design stamped

#128 Neel/updating page styles for mobile
  pages/document-upload.tsx
  pages/login.tsx
  src/components/Footer.tsx
  src/components/MissingDocAlert.tsx
  src/components/Navbar.tsx
  src/components/WelcomeToSDC.tsx
Labels: need dev review, need designer review, design stamped

#158 feat(admin/registrant): registrant profile page
  pages/admin/registrant/user/[id].tsx
  pages/api/student/index.ts
  pages/api/user/index.ts
  src/components/fileDownloadCard.tsx
  utils/hooks/useStudentsTableData.tsx
  utils/hooks/useVolunteersTableData.tsx
Labels: need dev review, need designer review, design stamped
