Repository uwblueprint/social-diversity-for-children, pull requests merged in 2021-10, with the labels that each got.

#77 feat(i18n): migrate to v8 and get i18n to work
  i18n.js
  next-i18next.config.js
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/locales/en/common.json
  public/locales/en/home.json
  public/locales/ja/common.json
  public/locales/ko/common.json
  public/locales/tr/common.json
  public/locales/tr/home.json
  public/locales/zh/common.json
  src/components/LanguageModal.tsx
  src/components/Navbar.tsx
  src/components/WelcomeToSDC.tsx
  yarn.lock
Labels: need dev review

#80 refactor parent/volunteer signup
  pages/parent-signup.tsx
  pages/parent/signup.tsx
  pages/signup.tsx
  pages/volunteer-signup.tsx
  pages/volunteer/signup.tsx
  src/components/parent-form/EmergInfoPage.tsx
  src/components/parent-form/HeardFromPage.tsx
  src/components/parent-form/IncomePage.tsx
  src/components/parent-form/LearningInfoPage.tsx
  src/components/parent-form/ParentCreatedPage.tsx
  src/components/parent-form/ParticipantInfoPage.tsx
  src/components/volunteer-form/CriminalPage.tsx
  src/components/volunteer-form/VolunteerCreatedPage.tsx
  src/components/volunteer-form/VolunteerDetailsPage.tsx
  src/components/volunteer-form/VolunteerInfoPage.tsx
  src/components/volunteer-form/VolunteerSkillsPage.tsx
Labels: need dev review, good to merge, urgent

#73 Added firstTimeSetup script
  fireTimeSetup.sh
Labels: good to merge

#78 feat(class): My classes page with multiple/single children workflow
  models/Class.ts
  models/Enroll.ts
  pages/api/enroll/child.ts
  pages/api/enroll/volunteer.ts
  pages/api/user/me.ts
  pages/class.tsx
  services/database/enroll.ts
  services/database/user.ts
  src/components/EnrollmentCard.tsx
  src/components/EnrollmentList.tsx
  src/components/Loading.tsx
  src/components/Navbar.tsx
  src/components/VolunteeringCard.tsx
  src/components/VolunteeringList.tsx
  utils/cardInfoUtil.ts
  utils/combineStudentEnrollment.ts
  utils/convertToListDisplay.ts
  utils/deleteClassRegistration.ts
  utils/deleteVolunteerRegistration.ts
  utils/fetcher.ts
  utils/useMe.ts
  utils/useParentRegistration.ts
  utils/useVolunteerRegistration.ts
Labels: need dev review, need designer review, design stamped

#79 feature - 404 error page
  pages/404.tsx
  public/icons/error-icon.svg
  src/components/icons/ErrorIcon.tsx
  src/components/icons/index.tsx
Labels: need dev review, need designer review, good to merge, design stamped, dev stamped

#84 chore(signup): fix up signup page + weekdayToString bugfix
  pages/parent-enrollment.tsx
  pages/signup.tsx
  src/styles/colours.ts
  utils/weekdayToString.ts
Labels: need dev review, need designer review, good to merge, design stamped, dev stamped

#82 Class Registration Agreement Components
  pages/media-release-form.tsx
  pages/participant-waiver.tsx
  pages/terms-and-conditions.tsx
Labels: need dev review, need designer review, good to merge, urgent, need changes, design stamped, dev stamped

#88 prod build dynamic route fix
  next-env.d.ts
  package.json
  pages/class.tsx
  pages/parent-enrollment.tsx
  yarn.lock
Labels: need dev review, urgent

#81 feature - empty state component for program/class views
  pages/index.tsx
  src/components/EmptyState.tsx
  src/styles/colours.ts
Labels: need dev review, need designer review, need changes, design stamped

#91 feat(translation): add locale link + translate
  package.json
  pages/404.tsx
  pages/api/class/index.ts
  pages/api/enroll/child.ts
  pages/api/enroll/volunteer.ts
  pages/api/mail/index.ts
  pages/api/program/[id].ts
  pages/api/program/index.ts
  pages/class.tsx
  pages/index.tsx
  pages/program-details/[pid].tsx
  pages/verify.tsx
  prisma/dev-seeds/class-translation.ts
  prisma/dev-seeds/program-translation.ts
  prisma/prod-seeds/class-translation.ts
  prisma/prod-seeds/program-translation.ts
  public/locales/en/common.json
  public/locales/en/form.json
  public/locales/ja/common.json
  public/locales/ja/form.json
  public/locales/ko/common.json
  public/locales/ko/form.json
  public/locales/zh/common.json
  public/locales/zh/form.json
  services/database/enroll.ts
  services/database/program-card-info.ts
  services/nodemailer/mail.ts
  src/components/ClassInfoCard.tsx
  src/components/ClassInfoModal.tsx
  src/components/CloseButton.tsx
  src/components/EnrollmentCard.tsx
  src/components/EnrollmentList.tsx
  src/components/Loading.tsx
  src/components/Navbar.tsx
  src/components/ProgramCard.tsx
  src/components/ProgramInfo.tsx
  src/components/SignInButton.tsx
  src/components/VolunteeringCard.tsx
  src/components/VolunteeringList.tsx
  src/components/WelcomeToSDC.tsx
  src/components/parent-form/ParentCreatedPage.tsx
  src/components/volunteer-form/VolunteerCreatedPage.tsx
  utils/cardInfoUtil.ts
  utils/convertToShortDateRange.ts
  utils/convertToShortDateString.ts
  utils/fetcherWithId.ts
  utils/mail/templateUtil.ts
  utils/translationUtil.ts
  utils/useParentRegistration.ts
  utils/useVolunteerRegistration.ts
  utils/weekdayToString.ts
  yarn.lock
Labels: need dev review, need designer review, good to merge, design stamped, dev stamped

#96 fix(icons) svg props fix
  src/components/DragAndDrop.tsx
  src/components/icons/ApprovedIcon.tsx
  src/components/icons/ErrorIcon.tsx
  src/components/icons/InfoIcon.tsx
  src/components/icons/MailReceivedIcon.tsx
  src/components/icons/MailSentIcon.tsx
  src/components/icons/PendingIcon.tsx
  src/components/icons/UploadIcon.tsx
Labels: need dev review, cleanup

#97 Converted All borderRadius Elements to Square
  pages/404.tsx
  pages/login.tsx
  pages/parent/signup.tsx
  pages/volunteer/signup.tsx
  src/components/EnrollmentCard.tsx
  src/components/LanguageModal.tsx
  src/components/SignInButton.tsx
  src/components/VolunteeringCard.tsx
  src/components/WelcomeToSDC.tsx
  src/components/parent-form/ParentCreatedPage.tsx
  src/components/volunteer-form/VolunteerCreatedPage.tsx
Labels: good to merge, cleanup

#83 Everything Signup
  .eslintrc
  models/Student.ts
  package.json
  pages/api/user/me.ts
  pages/parent/signup.tsx
  pages/volunteer/signup.tsx
  src/components/formFields/CheckBoxField.tsx
  src/components/formFields/DateField.tsx
  src/components/formFields/PhoneNumberField.tsx
  src/components/formFields/PostalCodeField.tsx
  src/components/formFields/ProvinceField.tsx
  src/components/formFields/TextField.tsx
  src/components/parent-form/EmergInfoPage.tsx
  src/components/parent-form/HealthInfoPage.tsx
  src/components/parent-form/HeardFromPage.tsx
  src/components/parent-form/LearningInfoPage.tsx
  src/components/parent-form/ParentCreatedPage.tsx
  src/components/parent-form/ParentInfoPage.tsx
  src/components/parent-form/ParticipantInfoPage.tsx
  src/components/volunteer-form/VolunteerCreatedPage.tsx
  src/components/volunteer-form/VolunteerDetailsPage.tsx
  src/components/volunteer-form/VolunteerInfoPage.tsx
  src/components/volunteer-form/VolunteerSkillsPage.tsx
  src/styles/colours.ts
  utils/useLocalStorage.ts
  utils/validation/user.ts
  yarn.lock
Labels: need dev review, need designer review, urgent, need changes, design stamped

#105 Neel/integate zoom meeting links for classes
  pages/api/class/meeting.ts
  pages/class.tsx
  services/aws/index.ts
  services/aws/ssm.ts
  src/components/EnrollmentCard.tsx
  src/components/VolunteeringCard.tsx
  utils/useGetZoomLink.ts
Labels: need dev review, good to merge, dev stamped

#102 feature - integrate criminal check + proof of income support
  pages/index.tsx
  src/components/MissingDocAlert.tsx
Labels: need dev review, need designer review, design stamped, dev stamped

#106 Finalized Parent Enrollment
  pages/api/enroll/child.ts
  pages/parent/enrollment.tsx
  pages/parent/signup.tsx
  pages/volunteer/signup.tsx
  src/components/ClassEnrollmentConfirm.tsx
  src/components/ClassInfoModal.tsx
  src/components/registration-form/DiscountPage.tsx
  src/components/registration-form/ParentEnrollFormWrapper.tsx
  src/components/registration-form/ParentEnrolledConfirmationPage.tsx
  src/components/registration-form/ProofOfIncomePage.tsx
  utils/createClassRegistration.ts
Labels: need dev review, need designer review, design stamped, dev stamped
